name: CI
on:
  push:
    branches:
    - master

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - run: pip install -r requirements.txt
    - run: sudo apt install latexmk wget texlive-xetex texlive-fonts-extra

    # Ubuntu's pandoc is out of date
    - run: wget https://github.com/jgm/pandoc/releases/download/2.11.3.2/pandoc-2.11.3.2-1-amd64.deb
    - run: sudo dpkg -i pandoc-2.11.3.2-1-amd64.deb

    - run: python build.py --pdf --html
    - run: mv html/output/* output

    - name: Deploy
      uses: peaceiris/actions-gh-pages@364c31d33bb99327c77b3a5438a83a357a6729ad # v3.4.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: output
